---
title: "Visualization Lab 2"
author: "Roshni Sundaramurthy (rossu809); Brian Masinde (brima748)"
date: "17 September 2018"
output:
  html_notebook:
    theme: journal
  html_document:
    df_print: paged
fontsize: 11pt
---

### Assignment 1. Perception Visualization

```{r data}
olive <- read.csv("olive.csv", sep = ",", header = TRUE)
```

```{r libraries}
library(ggplot2)
library(plotly)
```

```{r question1_a}
p_vs_o <- ggplot(olive, aes(x=oleic, y=palmitic,
                     color = linolenic)) +
  geom_point() 
  #xlab("")
p_vs_o
```

```{r cut_interval}
olive$linolenic2 <- cut_interval(olive$linolenic, n=4)
```


```{r question1_b}
p_vs_o2 <- ggplot(olive, aes(x=oleic, y=palmitic, color = linolenic2)) + 
  geom_point()

p_vs_o2
```

```{r question 2, warning=FALSE}
p_vs_o3 <- ggplot(olive, aes(palmitic, oleic)) +
  geom_point(aes(color=linolenic2, size=linolenic2)) +
  geom_spoke(aes(angle=as.numeric(linolenic2),radius=as.numeric(linolenic2)))

p_vs_o3
```

```{r Question3}
o_vs_e <- ggplot(olive, aes(x=oleic, y=eicosenoic, color = Region)) + 
  geom_point()
o_vs_e
```


```{r discretization}
olive$linoleic2 <- cut_interval(olive$linoleic, n=3)
olive$palmitic2 <- cut_interval(olive$palmitic, n=3)
olive$palmitoleic2 <- cut_interval(olive$palmitoleic, n=3)
```

```{r question4, warning=FALSE}
o_vs_e1 <- ggplot(olive, aes(x=oleic, y=eicosenoic)) + 
  geom_point(aes(color=linoleic2, size=palmitoleic2, shape=palmitic2))
o_vs_e1
```

```{r question5, warning=FALSE}
o_vs_e2 <- ggplot(olive, aes(x=oleic, y=eicosenoic)) + 
  geom_point(aes(color=Region, size=palmitoleic2, shape=palmitic2))

o_vs_e2
```

```{r question6}
plot_ly(data = olive, labels=~Area, type = 'pie', showlegend = F) %>%
  layout(title = 'Proportion of Oils from different regions',
        xaxis = list(showgrid = F, zeroline = F, showticklables = F),
         yaxis = list(showgrid = F, zeroline = F, showticklables = F))

```

